apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env-gcp
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://gcp-db-host:5432/mydb"
  SECRET_KEY: "shared-key"
  FLASK_ENV: "production"
  DEBUG: "False"
