# AWS Secret for Flask App - AWS RDS Credentials

apiVersion: v1
kind: Service
metadata:
  name: flask-app-aws-active
  namespace: default
  labels:
    app: flask-app-aws
spec:
  type: LoadBalancer
  selector:
    app: flask-app-aws
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-aws-preview
  namespace: default
  labels:
    app: flask-app-aws
spec:
  type: ClusterIP
  selector:
    app: flask-app-aws
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

