apiVersion: v1
kind: Service
metadata:
  name: flask-app-gcp-active
  namespace: default
  labels:
    app: flask-app-gcp
spec:
  type: LoadBalancer
  selector:
    app: flask-app-gcp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-gcp-preview
  namespace: default
  labels:
    app: flask-app-gcp
spec:
  type: ClusterIP
  selector:
    app: flask-app-gcp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

