apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "put-your-terraform-output-here"
  SECRET_KEY: "put-your-terraform-output-here"
  FLASK_ENV: "production"
  DEBUG: "False"
