apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "value-from-flask-app-secret"
  SECRET_KEY: "value-from-flask-app-secret"
  FLASK_ENV: "production"
  DEBUG: "False"
