# AWS Secret for Flask App - AWS RDS Credentials

apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env-aws
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "aws-database-url"
  SECRET_KEY: "aws-secret-key"
  FLASK_ENV: "production"
  DEBUG: "False"
 


# GCP Secret for Flask App - GCP Cloud SQL Credentials
apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env-gcp
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "gcp-database-url"
  SECRET_KEY: "gcp-secret-key"
  FLASK_ENV: "production"
  DEBUG: "False"

