# AWS Secret for Flask App - AWS RDS Credentials

apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env-aws
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "aws-database-url"
  SECRET_KEY: "shared-key"
  FLASK_ENV: "production"
  DEBUG: "False"
