apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    app: {{ include "flask-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-app.name" . }}
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: flask-app-env
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            # AWS database
            - name: AWS_DB_HOST
              value: "{{ .Values.db.awsHost | default "" }}"
            - name: AWS_DB_NAME
              value: "{{ .Values.db.awsName | default "" }}"
            - name: AWS_DB_USERNAME
              value: "{{ .Values.db.awsUsername | default "" }}"
            - name: AWS_DB_PASSWORD
              value: "{{ .Values.db.awsPassword | default "" }}"

            # GCP database
            - name: GCP_DB_HOST
              value: "{{ .Values.db.gcpHost | default "" }}"
            - name: GCP_DB_NAME
              value: "{{ .Values.db.gcpName | default "" }}"
            - name: GCP_DB_USERNAME
              value: "{{ .Values.db.gcpUsername | default "" }}"
            - name: GCP_DB_PASSWORD
              value: "{{ .Values.db.gcpPassword | default "" }}"

            # General app variables
            - name: SECRET_KEY
              value: "{{ .Values.secret | default "change_me" }}"
            - name: DB_PROVIDER
              value: "{{ .Values.db.provider | default "AWS" }}"
            - name: FLASK_ENV
              value: production

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

              





























# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-app
#   labels:
#     app: flask-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: flask-app
#   template:
#     metadata:
#       labels:
#         app: flask-app
#     spec:
#       containers:
#         - name: flask-app
#           image: your-docker-image:latest
#           ports:
#             - containerPort: 5000
#           envFrom:
#             - secretRef:
#                 name: flask-app-env
