apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask-app-multicloud
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cloud: "{{name}}"
  template:
    metadata:
      name: flask-app-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/kmkouokam/Refonte-Multi-Cloud-Production-Ready-project.git
        targetRevision: gitop
        path: argocd/{{name}}
      destination:
        server: "{{server}}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
