apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env-aws
  namespace: default               # Optional: use branch-specific namespace
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{DB_USER}}:{{DB_PASS}}@{{DB_ENDPOINT}}:5432/{{DB_NAME}}"
