apiVersion: v1
kind: Secret
metadata:
  name: flask-app-env-gcp
  namespace: default               # Optional, can be "default"
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{DB_USER}}:{{DB_PASS}}@{{DB_HOST}}:5432/{{DB_NAME}}"
